# Text measurement for ASS export word-wrap: a pure wrap algorithm plus a Pillow adapter that
# measures the static per-weight .ttf files generated by scripts/generate_font_weights.py.
from typing import Callable
from PIL import ImageFont

WEIGHT_LABELS = {400: "Regular", 500: "Medium", 600: "SemiBold", 700: "Bold"}

# font display name -> {weight: path to its generated static .ttf}. Updated together with
# scripts/generate_font_weights.py's SOURCES whenever a font is added or a weight mapping changes.
FONT_WEIGHT_PATHS = {
    "Public Sans": {
        400: "static/fonts/PublicSans-Regular.ttf",
        500: "static/fonts/PublicSans-Medium.ttf",
        600: "static/fonts/PublicSans-SemiBold.ttf",
        700: "static/fonts/PublicSans-Bold.ttf",
    },
    "JetBrains Mono": {
        400: "static/fonts/JetBrainsMono-Regular.ttf",
        500: "static/fonts/JetBrainsMono-Medium.ttf",
        700: "static/fonts/JetBrainsMono-Bold.ttf",
    },
}

def available_weights(font_name: str) -> list[int]:
    return sorted(FONT_WEIGHT_PATHS[font_name].keys())

def wrap_text(text: str, measure_width: Callable[[str], float], max_width_px: float) -> str:
    out_lines = []
    for paragraph in text.split("\n"):
        words = paragraph.split(" ")
        line = words[0]
        for word in words[1:]:
            candidate = f"{line} {word}"
            if measure_width(candidate) <= max_width_px:
                line = candidate
            else:
                out_lines.append(line)
                line = word
        out_lines.append(line)
    return "\n".join(out_lines)

def pil_font_measurer(font_name: str, size_px: int, weight: int = 400) -> Callable[[str], float]:
    path = FONT_WEIGHT_PATHS[font_name][weight]
    pil_font = ImageFont.truetype(path, size_px)

    def measure(text: str) -> float:
        left, _, right, _ = pil_font.getbbox(text)
        return right - left

    return measure
