# Text measurement for ASS export word-wrap: a pure wrap algorithm plus a Pillow adapter that
# measures the static per-weight .ttf files generated by scripts/generate_font_weights.py.
from typing import Callable
from PIL import ImageFont

WEIGHT_LABELS = {400: "Regular", 500: "Medium", 600: "SemiBold", 700: "Bold"}

# font display name -> {weight: path to its generated static .ttf}. Updated together with
# scripts/generate_font_weights.py's SOURCES whenever a font is added or a weight mapping changes.
FONT_WEIGHT_PATHS = {
    "Public Sans": {
        400: "static/fonts/PublicSans-Regular.ttf",
        500: "static/fonts/PublicSans-Medium.ttf",
        600: "static/fonts/PublicSans-SemiBold.ttf",
        700: "static/fonts/PublicSans-Bold.ttf",
    },
    "JetBrains Mono": {
        400: "static/fonts/JetBrainsMono-Regular.ttf",
        500: "static/fonts/JetBrainsMono-Medium.ttf",
        700: "static/fonts/JetBrainsMono-Bold.ttf",
    },
}

def available_weights(font_name: str) -> list[int]:
    return sorted(FONT_WEIGHT_PATHS.get(font_name, {}).keys())

def nearest_available_weight(font_name: str, weight: int) -> int:
    """Clamp an arbitrary weight to the closest one this font actually has a static file for,
    so callers picking a Fontname/measurer never reference a missing weight (falls back to a
    system font in libass, or KeyErrors the measurer)."""
    weights = available_weights(font_name)
    return min(weights, key=lambda w: abs(w - weight))

def wrap_text(text: str, measure_width: Callable[[str], float], max_width_px: float) -> str:
    out_lines = []
    for paragraph in text.split("\n"):
        words = paragraph.split(" ")
        line = words[0]
        for word in words[1:]:
            candidate = f"{line} {word}"
            if measure_width(candidate) <= max_width_px:
                line = candidate
            else:
                out_lines.append(line)
                line = word
        out_lines.append(line)
    return "\n".join(out_lines)

def wrap_text_runs(text: str, measure_range: Callable[[int, int], float], max_width_px: float) -> tuple[str, list[tuple[int, int]]]:
    """Like wrap_text, but measures each candidate line via measure_range(start, end) — character
    offsets into `text` — instead of a single whole-string measurer, so a line spanning multiple
    differently-styled FormatRuns is measured accurately. Line-break decisions still only ever
    happen at spaces (never mid-word), so the greedy algorithm itself is unchanged from wrap_text;
    only what gets measured changes. Returns the wrapped text (word-break spaces become \\n, same
    as wrap_text) plus each output line's (start, end) offsets into the original `text`."""
    out_lines: list[str] = []
    spans: list[tuple[int, int]] = []
    offset = 0
    for paragraph in text.split("\n"):
        words = paragraph.split(" ")
        word_starts = []
        pos = offset
        for word in words:
            word_starts.append(pos)
            pos += len(word) + 1  # +1 accounts for the space (or the paragraph's trailing \n)
        line_start = word_starts[0]
        line_end = line_start + len(words[0])
        for i in range(1, len(words)):
            candidate_end = word_starts[i] + len(words[i])
            if measure_range(line_start, candidate_end) <= max_width_px:
                line_end = candidate_end
            else:
                out_lines.append(text[line_start:line_end])
                spans.append((line_start, line_end))
                line_start = word_starts[i]
                line_end = word_starts[i] + len(words[i])
        out_lines.append(text[line_start:line_end])
        spans.append((line_start, line_end))
        offset += len(paragraph) + 1  # +1 accounts for the \n joining this paragraph to the next
    return "\n".join(out_lines), spans

def pil_font_measurer(font_name: str, size_px: int, weight: int = 400) -> Callable[[str], float]:
    path = FONT_WEIGHT_PATHS[font_name][weight]
    pil_font = ImageFont.truetype(path, size_px)

    def measure(text: str) -> float:
        left, _, right, _ = pil_font.getbbox(text)
        return right - left

    return measure
